### ISSUE TITLE
Add henare to owners

### ISSUE THREAD

**Issue by henare** [openaustralia/morph-cli#10]
@mlandauer So I can push 0.2.3 can you please run:

```
gem owner morph-cli -a henare.degan@gmail.com
```

Thank you :tulip:

**Comment by henare** [comment]
Hi @mlandauer, I'm hoping you removed your assignment by mistake. We can't release a new version of this gem until you run that one command above. Please do that as soon as you can so we can release the improvements made by volunteers @otherchirps and @chris48s in #9 and #11.

**Comment by mlandauer** [comment]
Hi @henare. Yes, I'm sorry I removed my assignment by mistake in an attempt to do some spring cleaning. This is now fixed.
